name: Release Merged PR

on:
  pull_request:
    types: [closed]

jobs:
  release-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Publish the release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          python -m pip install .
          python -m proj_flow github release --publish ON
